Fix istio control and data planes naming in documentation
apache/skywalking pull request #8475
Opened 2022-01-24 18:24 UTC by toffentoffen

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

2022-01-24 23:40 UTC, wu-sheng requested changes
Hi, Marc, I think you mis-change the submodules accidentally. Please make sure they are unchanged.

![image](https://user-images.githubusercontent.com/5441976/150883476-374d9504-b1e4-4c04-9eec-6261711261ae.png)

2022-01-25 08:59 UTC, toffentoffen commented
> Hi, Marc, I think you mis-change the submodules accidentally. Please make sure they are unchanged.
> 
> ![image](https://user-images.githubusercontent.com/5441976/150883476-374d9504-b1e4-4c04-9eec-6261711261ae.png)

yes sorry, you are totally right. My bad. Will fix it right away.

I don't know how I got those changes, I haven't worked with submodules allot.

```
$ git fetch upstream master
remote: Enumerating objects: 1048, done.
remote: Counting objects: 100% (1048/1048), done.
remote: Compressing objects: 100% (497/497), done.
remote: Total 1048 (delta 322), reused 942 (delta 269), pack-reused 0
Receiving objects: 100% (1048/1048), 306.86 KiB | 1.31 MiB/s, done.
Resolving deltas: 100% (322/322), completed with 32 local objects.
From github.com:apache/skywalking
 * branch                master     -> FETCH_HEAD
   62ef59466..2d13c8afd  master     -> upstream/master
Fetching submodule apm-protocol/apm-network/src/main/proto
git reFrom github.com:apache/skywalking-data-collect-protocol
   fbbe955..667134d  master     -> origin/master
 * [new tag]         v8.9.0     -> v8.9.0
 * [new tag]         v8.9.1     -> v8.9.1
Fetching submodule oap-server/server-query-plugin/query-graphql-plugin/src/main/resources/query-protocol
From github.com:apache/skywalking-query-protocol
   2c59ae0..d6e2947  master     -> origin/master
 * [new tag]         v8.9.0     -> v8.9.0
 * [new tag]         v8.9.1     -> v8.9.1
 
 
  $ git rebase upstream/master
  $ git status
  On branch fix-istio-planes-naming
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   apm-protocol/apm-network/src/main/proto (new commits)
	modified:   oap-server/server-query-plugin/query-graphql-plugin/src/main/resources/query-protocol (new commits)
```

After rebasing those new "problematic" files showed up.

I couldn't `git restore` or `git checkout -- ` them, the only think that worked after googling was `git submodule update --init --recursive` 🤷  Do you know why @wu-sheng ? I am curious.
Anyhow fixed the PR and force pushed the changes.

2022-01-25 09:02 UTC, wu-sheng commented
When you face a submodule update in the upstream, your git(local) will prefer to keep your local version. So, in this time, you need to revert the local change.

2022-01-25 09:16 UTC, wu-sheng approved these changes

2022-01-25 11:14 UTC, merged