nhance endpoint dependency analysis to support cross threads cases.
apache/skywalking pull request #8747
Opened 2022-03-25 13:41 UTC by wu-sheng

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking/blob/master/CHANGES.md).

* [**Breaking Change**] Remove **Deprecated responseCode** from sources, including Service, ServiceInstance, Endpoint
* Enhance endpoint dependency analysis to support cross threads cases. Refactor span analysis code structures. 
___

In our showcase and Java agent scenarios, there are several cross-thread tracing cases, we were not generating endpoint dependency if ref exists in local and exit span. In this PR, I am adding this missing part back.
Also, in case the downstream endpoint of the dependency is another local/exit span's operation name, which was not generating endpoint traffic before, I add traffic generation of both sides' endpoints of dependency.
Another important point that drives me to fix this is, in the new Booster UI, metrics of endpoint dependency are shown in a separate dashboard, which requires the endpoints of both sides existing in meta data, otherwise, nothing shows up.

For e2e, I updated the Java agent to the latest.

@kezhenxu94 @wankai123  Please verify this would enhance the endpoint dependency on the showcase.

2022-03-25 15:55 UTC, wankai123 approved these changes

2022-03-26 01:15 UTC, wankai123 requested changes
Needs more verify

2022-03-26 09:39 UTC, wu-sheng commented
* Remove `isNotNormal` service requirement when use alias to merge service topology from client side.

The above bug exists for nearly a year, when we add `isNormal` in v8, we should not add this condition. Peer alias should always be used for building topology from client-side relationship.

2022-03-26 11:20 UTC, wankai123 approved these changes

2022-03-26 12:00 UTC, merged